### Get Token
POST http://127.0.0.1:8081/auth/token
Content-Type: application/json

{
  "username": "SUPERVISOR_USER",
  "password": "SUPER@BAR"
}


### Test Token
GET http://127.0.0.1:8081/auth/info
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiZWhuYW0iLCJpYXQiOjE1OTg3MjUwNzYsImV4cCI6MTU5ODcyODY3Nn0.g5oAkymuy4TrUrJ3XwxQ0rBo14aoPkOJs2h11aYYFZI