### Get Token
POST http://127.0.0.1:8081/auth/token
Content-Type: application/json

{"username":"behnam","password":"behnam"}


### Test Token
GET http://127.0.0.1:8081/auth/info
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiZWhuYW0iLCJpYXQiOjE1OTg2MTIyMDYsImV4cCI6MTU5ODYxNTgwNn0.YFxpB2WhqY-Wv-ZrjpGqSn5_67eQSN68om2Q_uJrFVA