# call catalog find by id
POST http://127.0.0.1:8081/api/cartable/find-by-id
Content-Type: application/json

1

###
# call catalog save
POST http://127.0.0.1:8081/api/cartable/save
Content-Type: application/json

{
  "receiver": {
    "id": 1,
    "version": 0
  },
  "sender": {
    "id": 1
  },
  "contract": {
    "id": 2
  }
}

###
# call catalog update
POST http://127.0.0.1:8081/api/cartable/update
Content-Type: application/json

{
  "id": 3,
  "version": 0,
  "receiver": {
    "id": 1,
    "version": 0
  },
  "sender": {
    "id": 1
  },
  "contract": {
    "id": 1
  }
}


###
# call catalog find paging
POST http://127.0.0.1:8081/api/cartable/find-paging
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiZWhuYW0iLCJpYXQiOjE1OTg2Mjk0MTMsImV4cCI6MTU5ODYzMzAxM30.1UiJgfnGeRzlNtxxNUMLV7OEvTKx4KD5pj5-FT2HVTI

{
  "start": 0,
  "max": 3,
  "filters": [
    {
      "key": "contract.lendingNumber",
      "value": "3213",
      "operation": "EQUAL"
    }
  ]
}

###

