# call cartable find by id
POST http://127.0.0.1:8081/api/cartable/find-by-id
Content-Type: application/json

1

###
# call cartable find by id
POST http://127.0.0.1:8081/api/cartable/get-user-info
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJTVVBFUlZJU09SX1VTRVIiLCJpYXQiOjE2MDEwNDE2ODgsImV4cCI6MTYwMTA0NTI4OH0.SR0TMiQwWGH6fQkeCmeLbgc2N0DpUGW3I1R02YjUsjs

###
# call cartable save
POST http://127.0.0.1:8081/api/cartable/save
Content-Type: application/json

{
  "receiver": {
    "id": 1,
    "version": 0
  },
  "sender": {
    "id": 1
  },
  "contract": {
    "id": 2
  }
}

###
# call cartable update
POST http://127.0.0.1:8081/api/cartable/update
Content-Type: application/json

{
  "id": 3,
  "version": 0,
  "receiver": {
    "id": 1,
    "version": 0
  },
  "sender": {
    "id": 1
  },
  "contract": {
    "id": 1
  }
}


###
# call cartable find paging
POST http://127.0.0.1:8081/api/cartable/find-paging
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJTVVBFUlZJU09SX1VTRVIiLCJpYXQiOjE2MDY0ODAzNjYsImV4cCI6MTYwNjQ4Mzk2Nn0.ZzEgzNPe6vqbJFZAjKQMcl-ZawVY-2gJBhNUt8X-Bcs

{
  "start": 0,
  "max": 1,
  "filters": [
    {
      "key": "contract.customers.person.firstName",
      "value": "آ",
      "operation": "MATCH"
    } ,
    {
      "key": "contract.guarantors.person.firstName",
      "value": "آ",
      "operation": "MATCH"
    }
  ]
}

###
###
# call cartable save
POST http://127.0.0.1:8081/api/cartable/assign
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiZWhuYW0iLCJpYXQiOjE1OTg3MjUwNzYsImV4cCI6MTU5ODcyODY3Nn0.g5oAkymuy4TrUrJ3XwxQ0rBo14aoPkOJs2h11aYYFZI

{
  "assigneeId": 1,
  "contractId": 1,
  "status": "STATUS_1"
}
