# call pursuit find by id
POST http://127.0.0.1:8081/api/pursuit/find-by-id
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiZWhuYW0iLCJpYXQiOjE1OTg3MDEzNzYsImV4cCI6MTU5ODcwNDk3Nn0.sDtw1dBBs-m-94VHwVpoNNMLIPxZiIc5DejNlPj1_8U

202

###
# call pursuit find by id
POST http://127.0.0.1:8081/api/pursuit/find-by-contract
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiZWhuYW0iLCJpYXQiOjE1OTg3MDEzNzYsImV4cCI6MTU5ODcwNDk3Nn0.sDtw1dBBs-m-94VHwVpoNNMLIPxZiIc5DejNlPj1_8U

1

###
# call pursuit save
POST http://127.0.0.1:8081/api/pursuit/save
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiZWhuYW0iLCJpYXQiOjE1OTg3MDEzNzYsImV4cCI6MTU5ODcwNDk3Nn0.sDtw1dBBs-m-94VHwVpoNNMLIPxZiIc5DejNlPj1_8U

{
  "description": "توضیحات",
  "coordinateAppointment": true,
  "depositAppointment": true,
  "submitAccordingFinal": false,
  "nextPursuitDate": "2020-01-07",
  "customerDeposit": true,
  "pursuitType": 1,
  "resultType": 1,
  "payment": {
    "id": 1,
    "version": 0
  },
  "user": {
    "id": 1
  },
  "contract": {
    "id": 1
  }
}

###
# call pursuit update
POST http://127.0.0.1:8081/api/pursuit/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiZWhuYW0iLCJpYXQiOjE1OTg3MDEzNzYsImV4cCI6MTU5ODcwNDk3Nn0.sDtw1dBBs-m-94VHwVpoNNMLIPxZiIc5DejNlPj1_8U

{
  "id": 102,
  "version": 0,
  "description": "توضیحات dfs ",
  "coordinateAppointment": true,
  "depositAppointment": true,
  "submitAccordingFinal": false,
  "nextPursuitDate": "2020-01-07",
  "customerDeposit": true,
  "pursuitType": 0,
  "resultType": 1,
  "payment": {
    "id": 1,
    "version": 0
  },
  "user": {
    "id": 1
  },
  "contract": {
    "id": 1
  }
}


###
# call pursuit find paging
POST http://127.0.0.1:8081/api/pursuit/find-paging
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiZWhuYW0iLCJpYXQiOjE1OTg3MDEzNzYsImV4cCI6MTU5ODcwNDk3Nn0.sDtw1dBBs-m-94VHwVpoNNMLIPxZiIc5DejNlPj1_8U

{
  "start": 0,
  "max": 10,
  "filters": [
    {
      "key": "contract.id",
      "value": "1",
      "operation": "EQUAL"
    },
    {
      "key": "payment",
      "operation": "NOT_NULL"
    }
  ]
}

###

