package com.bar.behdavarcommon;

public interface AuthorityConstant {
    String UPLOAD_EXCEL = "upload_excel";
    String CONVERT = "convert";

    String GEO_DIVISION_SAVE = "GEO_DIVISION_SAVE";
    String GEO_DIVISION_UPDATE = "GEO_DIVISION_UPDATE";
    String GEO_DIVISION_DELETE = "GEO_DIVISION_DELETE";
    String GEO_DIVISION_VIEW = "GEO_DIVISION_VIEW";
    String GEO_DIVISION_SEARCH = "GEO_DIVISION_SEARCH";

    String ATTACHMENT_SAVE = "ATTACHMENT_SAVE";
    String ATTACHMENT_UPDATE = "ATTACHMENT_UPDATE";
    String ATTACHMENT_DELETE = "ATTACHMENT_DELETE";
    String ATTACHMENT_VIEW = "ATTACHMENT_VIEW";
    String ATTACHMENT_VIEW_BY_CONTRACT = "ATTACHMENT_VIEW_BY_CONTRACT";
    String ATTACHMENT_SEARCH = "ATTACHMENT_SEARCH";

    String CARTABLE_SAVE = "CARTABLE_SAVE";
    String CARTABLE_UPDATE = "CARTABLE_UPDATE";
    String CARTABLE_ASSIGN = "CARTABLE_ASSIGN";
    String CARTABLE_GET_USER_INFO = "CARTABLE_GET_USER_INFO";
    String CARTABLE_DELETE = "CARTABLE_DELETE";
    String CARTABLE_VIEW = "CARTABLE_VIEW";
    String CARTABLE_SEARCH = "CARTABLE_SEARCH";

    String CATALOG_SAVE = "CATALOG_SAVE";
    String CATALOG_UPDATE = "CATALOG_UPDATE";
    String CATALOG_DELETE = "CATALOG_DELETE";
    String CATALOG_VIEW = "CATALOG_VIEW";
    String CATALOG_SEARCH = "CATALOG_SEARCH";

    String CUSTOMER_SAVE = "CUSTOMER_SAVE";
    String CUSTOMER_UPDATE = "CUSTOMER_UPDATE";
    String CUSTOMER_DELETE = "CUSTOMER_DELETE";
    String CUSTOMER_VIEW = "CUSTOMER_VIEW";
    String CUSTOMER_VIEW_BY_CONTRACT = "CUSTOMER_VIEW_BY_CONTRACT";
    String CUSTOMER_SEARCH = "CUSTOMER_SEARCH";

    String GUARANTOR_SAVE = "GUARANTOR_SAVE";
    String GUARANTOR_UPDATE = "GUARANTOR_UPDATE";
    String GUARANTOR_DELETE = "GUARANTOR_DELETE";
    String GUARANTOR_VIEW = "GUARANTOR_VIEW";
    String GUARANTOR_VIEW_BY_CONTRACT = "GUARANTOR_VIEW_BY_CONTRACT";
    String GUARANTOR_SEARCH = "GUARANTOR_SEARCH";

    String PAYMENT_SAVE = "PAYMENT_SAVE";
    String PAYMENT_UPDATE = "PAYMENT_UPDATE";
    String PAYMENT_DELETE = "PAYMENT_DELETE";
    String PAYMENT_VIEW = "PAYMENT_VIEW";
    String PAYMENT_VIEW_BY_CONTRACT = "PAYMENT_VIEW_BY_CONTRACT";
    String PAYMENT_SEARCH = "PAYMENT_SEARCH";

    String PERSON_UPDATE = "PERSON_UPDATE";
    String PERSON_SUGGESTION = "PERSON_SUGGESTION";

    String PRIVILEGE_VIEW = "PRIVILEGE_VIEW";
    String PRIVILEGE_SEARCH = "PRIVILEGE_SEARCH";
    String PRIVILEGE_SUGGESTION = "PRIVILEGE_SUGGESTION";


}
