package com.bar.behdavarcommon;

public interface AuthorityConstant {
    String UPLOAD_EXCEL = "upload_excel";
    String CONVERT = "convert";

    String GEO_DIVISION_SAVE = "GEO_DIVISION_SAVE";
    String GEO_DIVISION_UPDATE = "GEO_DIVISION_UPDATE";
    String GEO_DIVISION_DELETE = "GEO_DIVISION_DELETE";
    String GEO_DIVISION_VIEW = "GEO_DIVISION_VIEW";
    String GEO_DIVISION_SEARCH = "GEO_DIVISION_SEARCH";

    String ATTACHMENT_SAVE = "ATTACHMENT_SAVE";
    String ATTACHMENT_UPDATE = "ATTACHMENT_UPDATE";
    String ATTACHMENT_DELETE = "ATTACHMENT_DELETE";
    String ATTACHMENT_VIEW = "ATTACHMENT_VIEW";
    String ATTACHMENT_VIEW_BY_CONTRACT = "ATTACHMENT_VIEW_BY_CONTRACT";
    String ATTACHMENT_SEARCH = "ATTACHMENT_SEARCH";

    String CARTABLE_SAVE = "CARTABLE_SAVE";
    String CARTABLE_UPDATE = "CARTABLE_UPDATE";
    String CARTABLE_ASSIGN = "CARTABLE_ASSIGN";
    String CARTABLE_GET_USER_INFO = "CARTABLE_GET_USER_INFO";
    String CARTABLE_DELETE = "CARTABLE_DELETE";
    String CARTABLE_VIEW = "CARTABLE_VIEW";
    String CARTABLE_SEARCH = "CARTABLE_SEARCH";

    String CATALOG_SAVE = "CATALOG_SAVE";
    String CATALOG_UPDATE = "CATALOG_UPDATE";
    String CATALOG_DELETE = "CATALOG_DELETE";
    String CATALOG_VIEW = "CATALOG_VIEW";
    String CATALOG_SEARCH = "CATALOG_SEARCH";

}
