export enum AuthorityConstantEnum {
  VIEW_MY_BASKET = 'VIEW_MY_BASKET',
  VIEW_SEARCH = 'VIEW_SEARCH',
  SEARCH_ALL = 'SEARCH_ALL',
  VIEW_USER_MANAGEMENT = 'VIEW_USER_MANAGEMENT',
  VIEW_DOCUMENT_MANAGEMENT = 'VIEW_DOCUMENT_MANAGEMENT',
  VIEW_DOCUMENT_ENTRY = 'VIEW_DOCUMENT_ENTRY',
  VIEW_REPORT = 'VIEW_REPORT',
  VIEW_UTILITY_TOOLS = 'VIEW_UTILITY_TOOLS',
}
