
export enum AuthorityConstantEnum {
  VIEW_USER_MANAGEMENT = 'VIEW_USER_MANAGEMENT',
  VIEW_SEARCH_MENU = 'VIEW_SEARCH_MENU',
  VIEW_DOCUMENT_ENTRY = 'VIEW_DOCUMENT_ENTRY',
  VIEW_UTILITY_TOOLS = 'VIEW_UTILITY_TOOLS',
}
